# Generated by Django 4.1.6 on 2023-02-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='refresh_token',
            new_name='access_secret',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='token',
            new_name='access_token',
        ),
    ]
