# Generated by Django 4.1.6 on 2023-02-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_refresh_token_subscriber_access_secret_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='access_secret',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='email',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='expires_at',
        ),
    ]
