# Generated by Django 4.1.6 on 2023-02-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_email_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='source',
        ),
        migrations.AddField(
            model_name='email',
            name='sender',
            field=models.EmailField(db_index=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='subject',
            field=models.CharField(db_index=True, max_length=256, null=True),
        ),
    ]
