# Generated by Django 4.1.6 on 2023-02-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_email_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='user',
        ),
        migrations.AddField(
            model_name='email',
            name='sender',
            field=models.EmailField(db_index=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='subject',
            field=models.CharField(db_index=True, max_length=256, null=True),
        ),
    ]
