# Generated by Django 4.1.6 on 2023-02-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_email_user_email_sender_email_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='source',
            field=models.TextField(null=True),
        ),
    ]
