# Generated by Django 4.1.6 on 2023-02-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_email_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='gmail_id',
            field=models.EmailField(db_index=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='label_id',
            field=models.EmailField(db_index=True, max_length=254, null=True),
        ),
    ]
