# Generated by Django 4.1.6 on 2023-02-24 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_email_gmail_id_email_label_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='gmail_id',
            new_name='email_id',
        ),
        migrations.RemoveField(
            model_name='email',
            name='label_id',
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_id', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='labels',
            field=models.ManyToManyField(blank=True, to='api.label'),
        ),
    ]
