# Generated by Django 4.1.6 on 2023-02-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_email_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_id',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
