# Generated by Django 4.1.6 on 2023-02-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_email_headline'),
        ('api', '0009_alter_email_email_id'),
    ]

    operations = [
    ]
