# Generated by Django 4.1.6 on 2023-03-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_0006_email_headline_0009_alter_email_email_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='body',
        ),
        migrations.RemoveField(
            model_name='email',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='email',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='email',
            name='source',
        ),
        migrations.RemoveField(
            model_name='email',
            name='subject',
        ),
    ]
