# Generated by Django 4.1.6 on 2023-03-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_email_body_remove_email_headline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
